[2023-10-17T20:32:40.527+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games_details.gcs_to_raw scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T20:32:40.534+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games_details.gcs_to_raw scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T20:32:40.534+0000] {taskinstance.py:1359} INFO - Starting attempt 8 of 8
[2023-10-17T20:32:40.544+0000] {taskinstance.py:1380} INFO - Executing <Task(LoadFileOperator): gcs_to_raw> on 2023-10-16 00:00:00+00:00
[2023-10-17T20:32:40.550+0000] {standard_task_runner.py:57} INFO - Started process 323 to run task
[2023-10-17T20:32:40.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'games_details', 'gcs_to_raw', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp3btpusdt']
[2023-10-17T20:32:40.555+0000] {standard_task_runner.py:85} INFO - Job 526: Subtask gcs_to_raw
[2023-10-17T20:32:40.587+0000] {task_command.py:415} INFO - Running <TaskInstance: games_details.gcs_to_raw scheduled__2023-10-16T00:00:00+00:00 [running]> on host df3af04ab639
[2023-10-17T20:32:40.645+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games_details' AIRFLOW_CTX_TASK_ID='gcs_to_raw' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-10-17T20:32:40.659+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:40.663+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:40.682+0000] {load_file.py:134} INFO - Loading gs://steamanalytics/raw/games_details_2023-10-17.csv into BaseTable(name='raw_games', conn_id='gcp', metadata=Metadata(schema='games', database=None), columns=[], temp=False) ...
[2023-10-17T20:32:40.687+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:40.688+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:40.751+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:40.752+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:40.757+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:40.757+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:41.405+0000] {bigquery.py:1094} INFO - Dataset Resource: Dataset(DatasetReference('pristine-flames-400818', 'games'))
[2023-10-17T20:32:41.412+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:41.413+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:41.417+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:41.419+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:41.424+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:41.425+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:42.864+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:42.865+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:42.870+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:42.871+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:43.307+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:43.309+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:43.318+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:43.319+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:43.326+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-10-17T20:32:43.327+0000] {base.py:73} INFO - Using connection ID 'gcp' for task execution.
[2023-10-17T20:32:45.121+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/sql/operators/load_file.py", line 131, in execute
    return self.load_data(input_file=self.input_file, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/sql/operators/load_file.py", line 136, in load_data
    return self.load_data_to_table(input_file, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/sql/operators/load_file.py", line 155, in load_data_to_table
    database.load_file_to_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/databases/base.py", line 513, in load_file_to_table
    self.create_table_if_needed(
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/databases/base.py", line 437, in create_table_if_needed
    self.create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/databases/base.py", line 355, in create_table
    self.create_table_using_schema_autodetection(
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/databases/base.py", line 306, in create_table_using_schema_autodetection
    source_dataframe = file.export_to_dataframe(nrows=LOAD_TABLE_AUTODETECT_ROWS_COUNT)
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/files/base.py", line 159, in export_to_dataframe
    return self.type.export_to_dataframe(stream, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/astro/files/types/csv.py", line 34, in export_to_dataframe
    df = pd.read_csv(stream, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-10-17T20:32:45.130+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=games_details, task_id=gcs_to_raw, execution_date=20231016T000000, start_date=20231017T203240, end_date=20231017T203245
[2023-10-17T20:32:45.142+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 526 for task gcs_to_raw (No columns to parse from file; 323)
[2023-10-17T20:32:45.179+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-17T20:32:45.204+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
