[2023-10-16T22:39:40.916+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T22:39:40.923+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T22:39:40.923+0000] {taskinstance.py:1359} INFO - Starting attempt 11 of 11
[2023-10-16T22:39:40.932+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2023-10-15 00:00:00+00:00
[2023-10-16T22:39:40.937+0000] {standard_task_runner.py:57} INFO - Started process 368 to run task
[2023-10-16T22:39:40.940+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'games_details', 'extract_data', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp9qu9h5rm']
[2023-10-16T22:39:40.943+0000] {standard_task_runner.py:85} INFO - Job 451: Subtask extract_data
[2023-10-16T22:39:40.978+0000] {task_command.py:415} INFO - Running <TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [running]> on host f300611457cd
[2023-10-16T22:39:41.037+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games_details' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-10-16T22:39:41.038+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,038 - mi_logger - INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T22:39:41.038+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,038 - mi_logger - INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T22:39:41.038+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T22:39:41.039+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T22:39:41.039+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T22:39:41.039+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,039 - mi_logger - INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T22:39:41.039+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T22:39:41.040+0000] {logging_mixin.py:151} INFO - {'DB_PASS': 'tomi', 'DB_NAME': 'steamAnalytics', 'DB_USER': 'tomi', 'DB_HOST': '192.168.0.88'}
[2023-10-16T22:39:41.063+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,063 - mi_logger - ERROR - Error al conectar a la base de datos: (1130, "172.31.0.5' is not allowed to connect to this MySQL server")
[2023-10-16T22:39:41.063+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,063 - mi_logger - ERROR - Error al conectar a la base de datos: (1130, "172.31.0.5' is not allowed to connect to this MySQL server")
[2023-10-16T22:39:41.063+0000] {cloudsql_connection.py:39} ERROR - Error al conectar a la base de datos: (1130, "172.31.0.5' is not allowed to connect to this MySQL server")
[2023-10-16T22:39:41.063+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,063 - mi_logger - INFO - Error al extraer datos: __enter__
[2023-10-16T22:39:41.063+0000] {log.py:232} WARNING - 2023-10-16 22:39:41,063 - mi_logger - INFO - Error al extraer datos: __enter__
[2023-10-16T22:39:41.063+0000] {extract_data.py:27} INFO - Error al extraer datos: __enter__
[2023-10-16T22:39:41.063+0000] {python.py:194} INFO - Done. Returned value was: ([], [])
[2023-10-16T22:39:41.081+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=games_details, task_id=extract_data, execution_date=20231015T000000, start_date=20231016T223940, end_date=20231016T223941
[2023-10-16T22:39:41.111+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T22:39:41.139+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
