[2023-10-16T21:14:37.563+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T21:14:37.575+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T21:14:37.576+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-16T21:14:37.592+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2023-10-15 00:00:00+00:00
[2023-10-16T21:14:37.597+0000] {standard_task_runner.py:57} INFO - Started process 431 to run task
[2023-10-16T21:14:37.606+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'games_details', 'extract_data', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '427', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpevtoayxa']
[2023-10-16T21:14:37.618+0000] {standard_task_runner.py:85} INFO - Job 427: Subtask extract_data
[2023-10-16T21:14:37.696+0000] {task_command.py:415} INFO - Running <TaskInstance: games_details.extract_data scheduled__2023-10-15T00:00:00+00:00 [running]> on host fa3bcf4e4257
[2023-10-16T21:14:37.833+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games_details' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-10-16T21:14:37.834+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,834 - mi_logger - INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T21:14:37.834+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,834 - mi_logger - INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T21:14:37.834+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_PASS
[2023-10-16T21:14:37.834+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,834 - mi_logger - INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T21:14:37.834+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,834 - mi_logger - INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T21:14:37.834+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_NAME
[2023-10-16T21:14:37.835+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,835 - mi_logger - INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T21:14:37.835+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,835 - mi_logger - INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T21:14:37.835+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_USER
[2023-10-16T21:14:37.835+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,835 - mi_logger - INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T21:14:37.835+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,835 - mi_logger - INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T21:14:37.835+0000] {configs.py:39} INFO - Variables de entorno establecidas con exito DB_HOST
[2023-10-16T21:14:37.835+0000] {logging_mixin.py:151} INFO - {'DB_PASS': 'tomi', 'DB_NAME': 'steamAnalytics', 'DB_USER': 'tomi', 'DB_HOST': '127.0.0.1'}
[2023-10-16T21:14:37.837+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,837 - mi_logger - ERROR - Error al conectar a la base de datos: 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
[2023-10-16T21:14:37.838+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,837 - mi_logger - ERROR - Error al conectar a la base de datos: 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
[2023-10-16T21:14:37.837+0000] {cloudsql_connection.py:39} ERROR - Error al conectar a la base de datos: 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3306' (111)
[2023-10-16T21:14:37.838+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,838 - mi_logger - INFO - Error al extraer datos: __enter__
[2023-10-16T21:14:37.838+0000] {log.py:232} WARNING - 2023-10-16 21:14:37,838 - mi_logger - INFO - Error al extraer datos: __enter__
[2023-10-16T21:14:37.838+0000] {extract_data.py:27} INFO - Error al extraer datos: __enter__
[2023-10-16T21:14:37.838+0000] {python.py:194} INFO - Done. Returned value was: ([], [])
[2023-10-16T21:14:37.880+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=games_details, task_id=extract_data, execution_date=20231015T000000, start_date=20231016T211437, end_date=20231016T211437
[2023-10-16T21:14:37.918+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T21:14:37.971+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
